// Interface automatically generated by schemas-to-ts

import { Fact } from '../../shared/interfaces/Fact';
import { Media } from '../../../common/schemas-to-ts/Media';
import { Fact_Plain } from '../../shared/interfaces/Fact';
import { Fact_NoRelations } from '../../shared/interfaces/Fact';

export interface About {
  subtitle: string;
  title?: string;
  description: string;
  fact?: Fact;
  video?: { data: Media };
  preview?: any;
}
export interface About_Plain {
  subtitle: string;
  title?: string;
  description: string;
  fact?: Fact_Plain;
  video?: Media;
  preview?: any;
}

export interface About_NoRelations {
  subtitle: string;
  title?: string;
  description: string;
  fact?: Fact_NoRelations;
  video?: number;
  preview?: any;
}

