// Interface automatically generated by schemas-to-ts

export interface BlokIstoriyaOKompanii {
  title: string;
  description: string;
}
export interface BlokIstoriyaOKompanii_Plain {
  title: string;
  description: string;
}

export interface BlokIstoriyaOKompanii_NoRelations {
  title: string;
  description: string;
}

