// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface BlokSOsnovatelemKompanii {
  text: string;
  photo: { data: Media };
}
export interface BlokSOsnovatelemKompanii_Plain {
  text: string;
  photo: Media;
}

export interface BlokSOsnovatelemKompanii_NoRelations {
  text: string;
  photo: number;
}

