// Interface automatically generated by schemas-to-ts

export interface History {
  title: string;
  description: string;
}
export interface History_Plain {
  title: string;
  description: string;
}

export interface History_NoRelations {
  title: string;
  description: string;
}

