// Interface automatically generated by schemas-to-ts

import { Form } from '../../shared/interfaces/Form';
import { Form_Plain } from '../../shared/interfaces/Form';
import { Form_NoRelations } from '../../shared/interfaces/Form';

export interface HorizontalForm {
  Form?: Form;
}
export interface HorizontalForm_Plain {
  Form?: Form_Plain;
}

export interface HorizontalForm_NoRelations {
  Form?: Form_NoRelations;
}

