// Interface automatically generated by schemas-to-ts

export interface MyKomanda {
  title: string;
  description1: string;
  description2: string;
}
export interface MyKomanda_Plain {
  title: string;
  description1: string;
  description2: string;
}

export interface MyKomanda_NoRelations {
  title: string;
  description1: string;
  description2: string;
}

