// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Strongs {
  title: string;
  description: string;
  image: { data: Media };
}
export interface Strongs_Plain {
  title: string;
  description: string;
  image: Media;
}

export interface Strongs_NoRelations {
  title: string;
  description: string;
  image: number;
}

