// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Review {
  id: number;
  attributes: {
    review: string;
    client_name: string;
    client_job: string;
    client_photo: { data: Media };
    img_review?: { data: Media };
  };
}
export interface Review_Plain {
  id: number;
  review: string;
  client_name: string;
  client_job: string;
  client_photo: Media;
  img_review?: Media;
}

export interface Review_NoRelations {
  id: number;
  review: string;
  client_name: string;
  client_job: string;
  client_photo: number;
  img_review?: number;
}

export interface Review_AdminPanelLifeCycle {
  id: number;
  review: string;
  client_name: string;
  client_job: string;
  client_photo: AdminPanelRelationPropertyModification<Media>;
  img_review?: AdminPanelRelationPropertyModification<Media>;
}
