// Interface automatically generated by schemas-to-ts

import { Strongs } from '../../../../components/block/interfaces/Strongs';
import { Strongs_Plain } from '../../../../components/block/interfaces/Strongs';
import { Strongs_NoRelations } from '../../../../components/block/interfaces/Strongs';

export interface Strength {
  id: number;
  attributes: {
    strengths: Strongs[];
  };
}
export interface Strength_Plain {
  id: number;
  strengths: Strongs_Plain[];
}

export interface Strength_NoRelations {
  id: number;
  strengths: Strongs_NoRelations[];
}

export interface Strength_AdminPanelLifeCycle {
  id: number;
  strengths: Strongs_Plain[];
}
