// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/block/interfaces/Hero';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { Hero_Plain } from '../../../../components/block/interfaces/Hero';
import { Hero_NoRelations } from '../../../../components/block/interfaces/Hero';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface StraniczaKarera {
  id: number;
  attributes: {
    hero: Hero;
    title: string;
    description: string;
    photo: { data: Media };
  };
}
export interface StraniczaKarera_Plain {
  id: number;
  hero: Hero_Plain;
  title: string;
  description: string;
  photo: Media;
}

export interface StraniczaKarera_NoRelations {
  id: number;
  hero: Hero_NoRelations;
  title: string;
  description: string;
  photo: number;
}

export interface StraniczaKarera_AdminPanelLifeCycle {
  id: number;
  hero: Hero_Plain;
  title: string;
  description: string;
  photo: AdminPanelRelationPropertyModification<Media>;
}
