// Interface automatically generated by schemas-to-ts

export interface PersonalnyeDannye {
  id: number;
  attributes: {
    title: string;
    content: string;
  };
}
export interface PersonalnyeDannye_Plain {
  id: number;
  title: string;
  content: string;
}

export interface PersonalnyeDannye_NoRelations {
  id: number;
  title: string;
  content: string;
}

export interface PersonalnyeDannye_AdminPanelLifeCycle {
  id: number;
  title: string;
  content: string;
}
