// Interface automatically generated by schemas-to-ts

export interface Button {
  name: string;
}
export interface Button_Plain {
  name: string;
}

export interface Button_NoRelations {
  name: string;
}

