// Interface automatically generated by schemas-to-ts

export interface Fact {
  text_1: string;
  fact: string;
  text_2?: string;
}
export interface Fact_Plain {
  text_1: string;
  fact: string;
  text_2?: string;
}

export interface Fact_NoRelations {
  text_1: string;
  fact: string;
  text_2?: string;
}

