// Interface automatically generated by schemas-to-ts

export interface Form {
  title: string;
  buttonName: string;
  description?: string;
}
export interface Form_Plain {
  title: string;
  buttonName: string;
  description?: string;
}

export interface Form_NoRelations {
  title: string;
  buttonName: string;
  description?: string;
}

