// Interface automatically generated by schemas-to-ts

export interface List {
  title: string;
}
export interface List_Plain {
  title: string;
}

export interface List_NoRelations {
  title: string;
}

