// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface MetaSocial {
  socialNetwork: 'Facebook' | 'Twitter';
  title: string;
  description: string;
  image?: { data: Media };
}
export interface MetaSocial_Plain {
  socialNetwork: 'Facebook' | 'Twitter';
  title: string;
  description: string;
  image?: Media;
}

export interface MetaSocial_NoRelations {
  socialNetwork: 'Facebook' | 'Twitter';
  title: string;
  description: string;
  image?: number;
}

