// Interface automatically generated by schemas-to-ts

export interface Sotrudnichestvo {
  id: number;
  attributes: {
    title: string;
    description: string;
  };
}
export interface Sotrudnichestvo_Plain {
  id: number;
  title: string;
  description: string;
}

export interface Sotrudnichestvo_NoRelations {
  id: number;
  title: string;
  description: string;
}

export interface Sotrudnichestvo_AdminPanelLifeCycle {
  id: number;
  title: string;
  description: string;
}
