// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Team {
  id: number;
  attributes: {
    name: string;
    photo: { data: Media };
    job: string;
    year: string;
    education: string;
    competencies: string;
  };
}
export interface Team_Plain {
  id: number;
  name: string;
  photo: Media;
  job: string;
  year: string;
  education: string;
  competencies: string;
}

export interface Team_NoRelations {
  id: number;
  name: string;
  photo: number;
  job: string;
  year: string;
  education: string;
  competencies: string;
}

export interface Team_AdminPanelLifeCycle {
  id: number;
  name: string;
  photo: AdminPanelRelationPropertyModification<Media>;
  job: string;
  year: string;
  education: string;
  competencies: string;
}
