// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/block/interfaces/Hero';
import { Hero_Plain } from '../../../../components/block/interfaces/Hero';
import { Hero_NoRelations } from '../../../../components/block/interfaces/Hero';

export interface Contact {
  id: number;
  attributes: {
    address: string;
    workingHours: string;
    phone: string;
    email: string;
    coordinates: string;
    hero: Hero;
  };
}
export interface Contact_Plain {
  id: number;
  address: string;
  workingHours: string;
  phone: string;
  email: string;
  coordinates: string;
  hero: Hero_Plain;
}

export interface Contact_NoRelations {
  id: number;
  address: string;
  workingHours: string;
  phone: string;
  email: string;
  coordinates: string;
  hero: Hero_NoRelations;
}

export interface Contact_AdminPanelLifeCycle {
  id: number;
  address: string;
  workingHours: string;
  phone: string;
  email: string;
  coordinates: string;
  hero: Hero_Plain;
}
