// Interface automatically generated by schemas-to-ts

export interface Contact {
  id: number;
  attributes: {
    address: string;
    workingHours: string;
    phone: string;
    email: string;
    coordinates: string;
  };
}
export interface Contact_Plain {
  id: number;
  address: string;
  workingHours: string;
  phone: string;
  email: string;
  coordinates: string;
}

export interface Contact_NoRelations {
  id: number;
  address: string;
  workingHours: string;
  phone: string;
  email: string;
  coordinates: string;
}

export interface Contact_AdminPanelLifeCycle {
  id: number;
  address: string;
  workingHours: string;
  phone: string;
  email: string;
  coordinates: string;
}
