// Interface automatically generated by schemas-to-ts

export interface Policy {
  id: number;
  attributes: {
    title: string;
    content: string;
  };
}
export interface Policy_Plain {
  id: number;
  title: string;
  content: string;
}

export interface Policy_NoRelations {
  id: number;
  title: string;
  content: string;
}

export interface Policy_AdminPanelLifeCycle {
  id: number;
  title: string;
  content: string;
}
