// Interface automatically generated by schemas-to-ts

import { Hero } from '../../../../components/block/interfaces/Hero';
import { Hero_Plain } from '../../../../components/block/interfaces/Hero';
import { Hero_NoRelations } from '../../../../components/block/interfaces/Hero';

export interface StraniczaOtzyvy {
  id: number;
  attributes: {
    hero: Hero;
  };
}
export interface StraniczaOtzyvy_Plain {
  id: number;
  hero: Hero_Plain;
}

export interface StraniczaOtzyvy_NoRelations {
  id: number;
  hero: Hero_NoRelations;
}

export interface StraniczaOtzyvy_AdminPanelLifeCycle {
  id: number;
  hero: Hero_Plain;
}
