// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Button } from '../../../../components/shared/interfaces/Button';
import { Result } from '../../../../components/shared/interfaces/Result';
import { Button_Plain } from '../../../../components/shared/interfaces/Button';
import { Result_Plain } from '../../../../components/shared/interfaces/Result';
import { Button_NoRelations } from '../../../../components/shared/interfaces/Button';
import { Result_NoRelations } from '../../../../components/shared/interfaces/Result';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Advantage {
  id: number;
  attributes: {
    title: string;
    description: string;
    image: { data: Media };
    button?: Button;
    result?: Result;
  };
}
export interface Advantage_Plain {
  id: number;
  title: string;
  description: string;
  image: Media;
  button?: Button_Plain;
  result?: Result_Plain;
}

export interface Advantage_NoRelations {
  id: number;
  title: string;
  description: string;
  image: number;
  button?: Button_NoRelations;
  result?: Result_NoRelations;
}

export interface Advantage_AdminPanelLifeCycle {
  id: number;
  title: string;
  description: string;
  image: AdminPanelRelationPropertyModification<Media>;
  button?: Button_Plain;
  result?: Result_Plain;
}
