// Interface automatically generated by schemas-to-ts

export interface Vacancie {
  id: number;
  attributes: {
    title: string;
    description: string;
    link: string;
  };
}
export interface Vacancie_Plain {
  id: number;
  title: string;
  description: string;
  link: string;
}

export interface Vacancie_NoRelations {
  id: number;
  title: string;
  description: string;
  link: string;
}

export interface Vacancie_AdminPanelLifeCycle {
  id: number;
  title: string;
  description: string;
  link: string;
}
