// Interface automatically generated by schemas-to-ts

import { BlokIstoriyaOKompanii } from '../../../../components/block/interfaces/BlokIstoriyaOKompanii';
import { BlokIstoriyaOKompanii_Plain } from '../../../../components/block/interfaces/BlokIstoriyaOKompanii';
import { BlokIstoriyaOKompanii_NoRelations } from '../../../../components/block/interfaces/BlokIstoriyaOKompanii';

export interface ONa {
  id: number;
  attributes: {
    title: string;
    description: string;
    fact_text: string;
    fact_number: string;
    fact_text_2: string;
    block_history: BlokIstoriyaOKompanii;
  };
}
export interface ONa_Plain {
  id: number;
  title: string;
  description: string;
  fact_text: string;
  fact_number: string;
  fact_text_2: string;
  block_history: BlokIstoriyaOKompanii_Plain;
}

export interface ONa_NoRelations {
  id: number;
  title: string;
  description: string;
  fact_text: string;
  fact_number: string;
  fact_text_2: string;
  block_history: BlokIstoriyaOKompanii_NoRelations;
}

export interface ONa_AdminPanelLifeCycle {
  id: number;
  title: string;
  description: string;
  fact_text: string;
  fact_number: string;
  fact_text_2: string;
  block_history: BlokIstoriyaOKompanii_Plain;
}
